### ISSUE TITLE
revamped function "makeFullLinks" returning empty array

### ISSUE THREAD

**Issue by Larsundso** [Larsundso/Ayako-v1.5#7]
**Describe the bug**
Revamped function "makeFullLinks" returning empty array.
(restored old version for now) @Pacmard 

**input**
`[ 'https://disboard.org/' ]`

**Expected output**
```
[
  {
    contentType: 'text/html; charset=UTF-8',
    href: 'https://disboard.org/',
    url: 'https://disboard.org/',
    hostname: 'disboard.org',
    baseURL: 'https://disboard.org',
    baseURLhostname: 'disboard.org'
  }
]
```

**Actual output**
`[]`

https://github.com/Larsundso/Ayako-v1.5/commit/79c76bfe05bfba22b978720901a88ccedf04a933

~ Line 504
~ Line 499

**Comment by Pacmard** [comment]
a5ac7d270863f84498d95b5f5e9e1e0a9eb96cbd
